### ISSUE TITLE
아군에게 주는 데미지 정보를 받아오는 방법?

### ISSUE THREAD

**Issue by Nopied** [TeamPotry/plugins_in_FF2#3]
`SDKHook`의 `OnTakeDamage`은 아군에게 주는 데미지를 폭발형 공격만 받아올 수 있음.

일단 모든 무기의 공격에서 데미지 정보를 받아오게 하려면 저 방법이 아닌 다른 방법이 필요합니다.

구하게 되면 여기에 적어보죠.
알고 계시면 좀 도와주세요..

**Comment by whooyet** [comment]
새퍼 스턴에 걸려 있을 동안만 mp_friendlyfire 1 시킨다.

시키는 동안 아군에게 데미지를 줄 수 없다!

public Action:Event_OnTakeDamage(victim, &attacker, &inflictor, &Float:damage, &damagetype, &weapon, Float:damageForce[3], Float:damagePosition[3], damagecustom){
	
	if (IsValidClient(victim) && IsValidClient(attacker) && (victim != attacker))
	{
		if(GetClientTeam(victim) == GetClientTeam(attacker))
		{
			PrintToChatAll("%.1f", damage);
			damage = 0.0;
			return Plugin_Changed;
		}
	}
	return Plugin_Continue;
}

일단 생각나는건 이것뿐...

**Comment by Nopied** [comment]
@whooyet 그것도 좋은데 뭔가 간결하게 할 방법이 있었으면 좋겠네요.
